### ISSUE TITLE
Issue when reproducing iSpikformer results on Electricity dataset

### ISSUE THREAD

**Issue by huangrenzhuo** [microsoft/SeqSNN#24]
Hello, I'm trying to reproduce the results of iSpikformer as described in the paper "Efficient and Effective Time-Series Forecasting with Spiking Neural Networks", but my experimental results on the Electricity dataset differ significantly from those reported. I noticed the paper mentions averaging results across 3 random seeds — could you clarify which specific seeds were used in the original experiments?

Below are my configuration details and outcomes
```
_base_:
- ../dataset/electricity.yml
_custom_imports_:
- SeqSNN.network
- SeqSNN.dataset
- SeqSNN.runner

data:
  raw_label: False
  window: 168
  horizon: 24
  normalize: 3

runner:
  type: vsts
  task: regression
  optimizer: Adam
  lr: 0.0001
  weight_decay: 0.0
  loss_fn: mse
  metrics: [r2, rrse]
  observe: loss
  batch_size: 32
  out_size: 24
  aggregate: False
  early_stop: 30
  denormalize: True
  lower_is_better: True
  max_epoches: 1000
  valid_variates: 321

network:
  type: iSpikformer
  dim: 256
  d_ff: 1024
  depths: 2
  num_steps: 4
  heads: 8
  encoder_type: conv
```

![Image](https://github.com/user-attachments/assets/88d47834-0fb4-40f6-8c06-0ade0bdcdacc)
